# Site settings
title: Monitoring Art for Grafana from Monitoring Artist
email: ""
description: "Piece of Art for your Grafana"
url: "http://www.monitoringart.com"
baseurl: ""

# Owner/author information
owner:
  name:   Monitoring Artist
  avatar: avatar.png
  favicon: favicon.ico
  info: Grafana Monitoring Art datasources

# Internal nav
nav:
  - INSTALL MONITORING ART: "https://github.com/monitoringartist/grafana-monitoring-art#instalationss"

# All translation keys
translations:
 # 404.html
  permalink: "/404.html"

# Server
destination:      	 ./_site
port:             	 4000

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
paginate_path: "/journal/page:num/"
permalink: "/journal/:title/"
categories_path: "/journal/category/"
tags_path: "/journal/tag/"
gems: 
 - jekyll-paginate
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
